version: "3.5"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres:alpine3.18
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    ports:
      - "5050:80"
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_EMAIL=email@domail.com
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
volumes:
  postgres-data:
    external: true
    name: postgres-data
  pgadmin4-data:
    external: true
    name: pgadmin4-data
